version: '3.8'

services:
  client-db:
    image: postgres:latest
    container_name: client-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=client-db
    ports:
      - "5434:5432"

  client:
    image: julioborges05/ordermanagement-client
    container_name: ordermanagement-client
    environment:
      - DB_URL=jdbc:postgresql://client-db:5432/client-db
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "8080:8080"